version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock

  backend-test:
    image: snakee/golang-junit:1.21
    working_dir: /app
    volumes:
      - ./bug-tracker-backend:/app
    command: ["go", "test", "./..."]

volumes:
  jenkins_home: